# SPDX-FileCopyrightText: Copyright (c) 2016-2026 SeedRamp
# SPDX-License-Identifier: MIT
---
AllCops:
  NewCops: enable
Security/Eval:
  Enabled: false
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
