# SPDX-FileCopyrightText: Copyright (c) 2016-2026 SeedRamp
# SPDX-License-Identifier: MIT
---
scss_files: 'sass/**/*.scss'

linters:
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
